services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3333:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  grafana-storage: