services:
  test:
    image: ubuntu
    command: printenv GLOBALVARFILE LOCALVARFILE LOCALVAR TZ NFSSERVER
    env_file:
      - ../.env.global
    environment:
      - LOCALVARFILE=${LOCALVARFILE}
      - LOCALVAR=local_var_value