services:
  test:
    image: ubuntu
    command: printenv GLOBALVARFILE LOCALVARFILE LOCALVAR TZ NFSSERVER
    env_file:
      - /home/$USER/dev/homelab/docker/.env.global
    environment:
      - LOCALVARFILE=${LOCALVARFILE}
      - LOCALVAR=local_var_value