services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    #network_mode: 'host'
    runtime: nvidia
    deploy:    # <------------- Add this section for NVIDIA GPU Support ------------->
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 1900:1900/udp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - nfs_media:/media
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      #- ./path/to/fonts:/usr/local/share/fonts/custom
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
      - TZ=${TZ}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  nfs_media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/your/nfs/path