x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always


services:
  apache:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: httpd:latest
    container_name: basic_httpd
    ports:
      - '80:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs
    environment:
      - TZ=${TZ}
