services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    ports:
      - 5800:5800
    volumes:
      - ./config:/config:rw
      - nfs_store1:/storage/nfs_store1:ro
      - nfs_store2:/storage/nfs_store2:rw
    environment:
      - TZ={TZ}
      - LANG=en_AU.UTF-8
      - CRASHPLAN_SRV_MAX_MEM=4096M

volumes:
  nfs_store1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSSERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/your/nfs/path
  nfs_store2:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSSERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/your/nfs/path
