name: ollama
services:
    ollama:
        environment:
            - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        image: ollama/ollama
        restart: always
volumes:
    ollama:
        external: true
        name: ollama
