#comment: This is a simple workflow that deploys the code to the self-hosted runner
#comment: when a push event is triggered on the main branch.
name: first workflow

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
