#Workflow to checkout the main branch
name: Production Workflow Runner

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: main


