name: Prod Workflow Runner

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 
        run: |
          echo "docker step 1"
          docker ps

